require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'drb_protocol_drubyws.gemspec'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
